# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sdkman < Formula
  desc "A tool for managing parallel versions of multiple Software Development Kits"
  homepage "https://github.com/palindrom615/sdkman"
  version "0.4.16"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/palindrom615/sdkman/releases/download/v0.4.16/sdkman_0.4.16_Darwin_x86_64.tar.gz"
      sha256 "55a43dedb611f604ac5b71ab0b06aa1aeffaf32e6d4a73ec1ec79493ee80baae"
    end
    if Hardware::CPU.arm?
      url "https://github.com/palindrom615/sdkman/releases/download/v0.4.16/sdkman_0.4.16_Darwin_arm64.tar.gz"
      sha256 "6b23515f90811cb487a1d6bc53fafd70037a065a40cc5cba6665e87f3403189b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/palindrom615/sdkman/releases/download/v0.4.16/sdkman_0.4.16_Linux_x86_64.tar.gz"
      sha256 "e4f790c0cbdf419dd4622992a9b48be73469284a86803cb58f41bbc9fadba552"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/palindrom615/sdkman/releases/download/v0.4.16/sdkman_0.4.16_Linux_armv6.tar.gz"
      sha256 "53fda8221c3971d1b46c7c9c34f98401711f3994794a8855f568bb0ec2575198"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/palindrom615/sdkman/releases/download/v0.4.16/sdkman_0.4.16_Linux_arm64.tar.gz"
      sha256 "c2c9f13ec8e15579561af648eefec1e47bb18b981dc598a4e44ee45410db125e"
    end
  end

  def install
    bin.install "sdkman"
  end
end
